"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import styles from "./layout.module.css";
import ProductContextProvider from "@/context/ProductContext/ProductContextProvider";
import { Navbar } from "@/components";
import CartContextProvider from "@/context/CartContext/CartContextProvider";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const style = `${inter.className} ${styles.rootLayout}`;
  return (
    <html lang="en">
      <body className={style}>
        {/* <Head>
          <title>Qkart</title>
        </Head> */}
        <ProductContextProvider>
          <CartContextProvider>
            <Navbar />
            {children}
          </CartContextProvider>
        </ProductContextProvider>
      </body>
    </html>
  );
}
